# Generated by Django 5.2.4 on 2025-07-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('pla', 'PLA'), ('abs', 'ABS'), ('petg', 'PETG'), ('resin', 'Resin')], max_length=20)),
                ('quality', models.CharField(choices=[('0.3', 'Черновое (0.3мм)'), ('0.2', 'Стандартное (0.2мм)'), ('0.15', 'Высокое (0.15мм)'), ('0.1', 'Ультра (0.1мм)')], max_length=20)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=40)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[('Новый', 'New'), ('В обработке', 'In Review'), ('Печать', 'Printing'), ('Отправлено в доставку', 'Shipped To Delivery'), ('Доставляется', 'In Delivery'), ('Доставлен', 'Delivered'), ('Выполнен', 'Done'), ('Возврат', 'Returned')], default='Новый')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=200)),
                ('size', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('note', models.TextField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
        ),
    ]
